[package]
name = "linkpearl-ffi"
description = "The C ABI in include/linkpearl.h"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
name = "linkpearl"
crate-type = ["cdylib", "rlib"]

[dependencies]
linkpearl-core = { path = "../linkpearl-core" }
data-encoding.workspace = true

[dev-dependencies]
tempfile = "3"
